import { Modal, Flex, Typography, Button, Input, Alert, Space, message, Steps, Divider } from "antd";
import { useState, useEffect } from "react";
import { QRCodeSVG } from "qrcode.react";
import useApiRequest from "@/modules/api/useApiRequest";
import mfaService, { TotpSetupResponse } from "@/modules/user/mfaService";
import "./TotpSetupModal.css";

const { Text } = Typography;

type Props = {
  visible: boolean;
  onCancel: () => void;
  onSuccess: () => void;
};

export default function TotpSetupModal({ visible, onCancel, onSuccess }: Props) {
  const [currentStep, setCurrentStep] = useState<number>(0);
  const [setupData, setSetupData] = useState<TotpSetupResponse | null>(null);
  const [showSecret, setShowSecret] = useState(false);
  const [code, setCode] = useState("");
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [secret, setSecret] = useState<string>("");

  // Setup API call
  const { execute: doSetup, error: setupError } = useApiRequest({
    action: () => mfaService.setupTotp(),
    onReturn: (data) => {
      setSetupData(data);
      setSecret(data.secret || "");
    },
  });

  // Verify API call
  const { loading: verifyLoading, execute: doVerify, error: verifyError } = useApiRequest({
    action: () => mfaService.verifyTotp(code),
    onReturn: () => {
      setCurrentStep(1); // Move to backup codes step
      generateCodes();
    },
  });

  // Generate backup codes
  const { execute: generateCodes, loading: backupLoading } = useApiRequest({
    action: () => mfaService.generateBackupCodes(),
    onReturn: (data) => {
      setBackupCodes(data.codes);
    },
  });

  useEffect(() => {
    if (visible) {
      setCurrentStep(0);
      setCode("");
      setShowSecret(false);
      doSetup();
    }
  }, [visible]);

  const handleVerify = () => {
    if (code.length === 6) {
      doVerify();
    }
  };


  const handleCopyBackupCodes = () => {
    navigator.clipboard.writeText(backupCodes.join("\n"));
    message.success("Backup codes copied to clipboard");
  };

  const handleDownloadBackupCodes = () => {
    const element = document.createElement("a");
    const file = new Blob([backupCodes.join("\n")], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "terrakube-backup-codes.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleFinish = () => {
    onSuccess();
    onCancel();
  };

  const renderSetupStep = () => (
    <div className="totp-setup-content">
      {setupError && <Alert type="error" title="Failed to load QR code" description={setupError.message} style={{ marginBottom: 16 }} />}

      <div className="setup-instructions">
        <p className="instruction-intro">
          Connect an authenticator app that generates verification codes. You can use the codes when we need to verify your identity.
        </p>
        <ol className="instruction-steps">
          <li>Download and install an authenticator app on your mobile device.</li>
          <li>Use the app to scan this QR code.</li>
          <li>Enter the code generated by the app.</li>
        </ol>
      </div>

      <div className="qr-section">
        <div className="qr-code-wrapper">
          {setupData?.qrCodeBase64 ? (
            <img 
              src={`data:image/png;base64,${setupData.qrCodeBase64}`} 
              alt="TOTP QR Code" 
              className="qr-image"
            />
          ) : setupData?.qrCodeUri ? (
            <QRCodeSVG value={setupData.qrCodeUri} size={180} level="H" bgColor="#ffffff" fgColor="#000000" />
          ) : (
            <div className="qr-placeholder" />
          )}
        </div>
      </div>

      <div className="manual-entry-section">
        <Button 
          type="link" 
          className="cant-scan-link"
          onClick={() => setShowSecret(!showSecret)}
        >
          {showSecret ? "Hide Manual Key" : "I Can't Scan the QR Code"}
        </Button>

        {showSecret && (
          <div className="manual-key-panel">
            <Text className="key-label">Key</Text>
            <div className="key-box">
              <Text className="key-value" copyable={{ tooltips: ['Copy', 'Copied!'] }}>
                {secret || setupData?.secret || "Not available"}
              </Text>
            </div>
          </div>
        )}
      </div>

      <Divider />

      <form className="verification-section" onSubmit={(e) => { e.preventDefault(); handleVerify(); }}>
        <Text className="verification-label">Verification Code</Text>
        <Input 
          id="totp-setup-code"
          name="totp-code"
          autoComplete="one-time-code"
          inputMode="numeric"
          pattern="[0-9]*"
          value={code} 
          onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
          placeholder="Enter 6-digit code"
          maxLength={6}
          className="verification-input"
          autoFocus={!!setupData}
        />
        {verifyError && <Text type="danger" style={{ marginTop: 8, display: 'block' }}>{verifyError.message || "Verification failed"}</Text>}

        <div className="action-buttons">
          <Button onClick={onCancel}>Cancel</Button>
          <Button 
            type="primary" 
            htmlType="submit"
            loading={verifyLoading} 
            disabled={code.length !== 6}
          >
            Connect
          </Button>
        </div>
      </form>
    </div>
  );

  const renderBackupStep = () => (
    <Space direction="vertical" size="large" style={{ width: "100%" }}>
      <Alert
        title="Save your backup codes"
        description="If you lose access to your device, these codes are the only way to access your account. Save them in a secure place."
        type="warning"
        showIcon
      />

      <div className="backup-codes-grid">
        {backupCodes.map((code, index) => (
          <div key={index} className="backup-code">
            {code}
          </div>
        ))}
        {backupLoading && <Text>Generating codes...</Text>}
      </div>

      <Flex justify="center" gap="middle">
        <Button onClick={handleCopyBackupCodes}>Copy Codes</Button>
        <Button onClick={handleDownloadBackupCodes}>Download</Button>
      </Flex>

      <Flex justify="end" style={{ marginTop: 24 }}>
        <Button type="primary" onClick={handleFinish}>
          I have saved my codes
        </Button>
      </Flex>
    </Space>
  );

  return (
    <Modal
      className="totp-setup-modal"
      open={visible}
      title="Set up Two-Factor Authentication"
      onCancel={onCancel}
      footer={null}
      width={500}
      destroyOnHidden
      mask={{ closable: false }}
    >
      <Steps
        current={currentStep}
        items={[
          { title: "Scan Code" },
          { title: "Save Backup Codes" },
        ]}
        style={{ marginBottom: 24 }}
      />
      
      <div className="step-content">
        {currentStep === 0 ? renderSetupStep() : renderBackupStep()}
      </div>
    </Modal>
  );
}
